### ISSUE TITLE
Bug reporting

### ISSUE THREAD

**Issue by lx0095** [keyunluo/python-ffm#1]
CentOS
in ffm.py
line:301         y_true = val_data.labels
=> y_true = [int(i) for i in val_data.labels]
on my machine print(set(y_true)) shows ['0','1'] while numpy could not recognize it as binary
[0,1] works

and add type cast in wrap_dataset would help reading data from texts :)
line: 105        node.f = int(f)
line: 106        node.j = int(j)
line: 107        node.v = float(v)
line: 119        d.label = float(y)

**Comment by keyunluo** [comment]
Thank you for your report.
