### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by CXY573** [keyunluo/python-ffm#3]
IndexError                                Traceback (most recent call last)
<ipython-input-9-b45ddf9f5a13> in <module>()
----> 1 import ffm.ffm as ffm

~/比赛/Tencent/ffm/ffm/ffm.py in <module>()
      3 import os
      4 path = os.path.dirname(os.path.abspath(__file__))
----> 5 libffm_file = [i for i in os.listdir(path) if i.startswith('libffm.')][0]
      6 lib_path = path + '/' + libffm_file
      7 

IndexError: list index out of range

**Comment by keyunluo** [comment]
可以直接改成.so文件的绝对路径。另外此比赛数据量大，这个包并不适合，可使用xlearn。
